baseURL = "/"
languageCode = "en-us"
title = "domainr-node"
theme = "cayman"

disableKinds = ["taxonomy","taxonomyTerm"]

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
project_name = "domainr-node"
project_tagline = "💻 domainr-node is a Domainr API client written for Node that fully supports both the standard and enterprise versions."
footer = "© [Marvin Schopf](https://www.marvinschopf.com)"

[menu]
[[menu.nav]]
name = "View on GitHub"
url = "https://github.com/marvinschopf/domainr-node"
weight = 1
[[menu.nav]]
name = "View on NPM"
url = "https://www.npmjs.com/package/domainr-node"
weight = 2